#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (0 << 8))
#define MAP_SLATEPORT_CITY      (1 | (0 << 8))
#define MAP_MAUVILLE_CITY       (2 | (0 << 8))
#define MAP_RUSTBORO_CITY       (3 | (0 << 8))
#define MAP_FORTREE_CITY        (4 | (0 << 8))
#define MAP_LILYCOVE_CITY       (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (0 << 8))
#define MAP_OLDALE_TOWN         (10 | (0 << 8))
#define MAP_DEWFORD_TOWN        (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (0 << 8))
#define MAP_ROUTE101            (16 | (0 << 8))
#define MAP_ROUTE102            (17 | (0 << 8))
#define MAP_ROUTE103            (18 | (0 << 8))
#define MAP_ROUTE104            (19 | (0 << 8))
#define MAP_ROUTE105            (20 | (0 << 8))
#define MAP_ROUTE106            (21 | (0 << 8))
#define MAP_ROUTE107            (22 | (0 << 8))
#define MAP_ROUTE108            (23 | (0 << 8))
#define MAP_ROUTE109            (24 | (0 << 8))
#define MAP_ROUTE111            (25 | (0 << 8))
#define MAP_ROUTE112            (26 | (0 << 8))
#define MAP_ROUTE113            (27 | (0 << 8))
#define MAP_ROUTE114            (28 | (0 << 8))
#define MAP_ROUTE115            (29 | (0 << 8))
#define MAP_ROUTE116            (30 | (0 << 8))
#define MAP_ROUTE117            (31 | (0 << 8))
#define MAP_ROUTE118            (32 | (0 << 8))
#define MAP_ROUTE119            (33 | (0 << 8))
#define MAP_ROUTE120            (34 | (0 << 8))
#define MAP_ROUTE121            (35 | (0 << 8))
#define MAP_ROUTE122            (36 | (0 << 8))
#define MAP_ROUTE123            (37 | (0 << 8))
#define MAP_ROUTE124            (38 | (0 << 8))
#define MAP_ROUTE125            (39 | (0 << 8))
#define MAP_ROUTE126            (40 | (0 << 8))
#define MAP_ROUTE127            (41 | (0 << 8))
#define MAP_ROUTE128            (42 | (0 << 8))
#define MAP_ROUTE129            (43 | (0 << 8))
#define MAP_ROUTE130            (44 | (0 << 8))
#define MAP_ROUTE131            (45 | (0 << 8))
#define MAP_ROUTE132            (46 | (0 << 8))
#define MAP_ROUTE133            (47 | (0 << 8))
#define MAP_ROUTE134            (48 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124 (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126 (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127 (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128 (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129 (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105 (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125 (55 | (0 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (3 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (3 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (3 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (3 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (4 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (8 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (8 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (8 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (9 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (9 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (9 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (9 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (10 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (11 | (9 << 8))
#define MAP_SLATEPORT_CITY_MART                    (12 | (9 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (10 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (10 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (10 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (11 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (11 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (11 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (11 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (12 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (12 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (12 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (13 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (13 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (13 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (10 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (11 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (12 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (13 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (14 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (15 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (16 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (17 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (18 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (19 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (20 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (21 | (13 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (14 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (15 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// gMapGroup_Dungeons
#define MAP_UNDERWATER_SOOTOPOLIS_CITY (0 | (17 << 8))
#define MAP_DESERT_RUINS               (1 | (17 << 8))
#define MAP_GRANITE_CAVE_1F            (2 | (17 << 8))
#define MAP_GRANITE_CAVE_B1F           (3 | (17 << 8))
#define MAP_GRANITE_CAVE_B2F           (4 | (17 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM  (5 | (17 << 8))
#define MAP_PETALBURG_WOODS            (6 | (17 << 8))
#define MAP_JAGGED_PASS                (7 | (17 << 8))
#define MAP_FIERY_PATH                 (8 | (17 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN (9 | (17 << 8))
#define MAP_ISLAND_CAVE                (10 | (17 << 8))
#define MAP_UNDERWATER_ROUTE134        (11 | (17 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER  (12 | (17 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (18 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (18 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (18 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (18 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (18 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (18 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (18 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (18 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (18 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (18 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (18 << 8))
#define MAP_TRADE_CENTER             (25 | (18 << 8))
#define MAP_RECORD_CORNER            (26 | (18 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (18 << 8))
#define MAP_CONTEST_HALL             (28 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (18 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (18 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (18 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (18 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (18 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (18 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (18 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (41 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (42 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (43 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (44 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (45 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (46 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (47 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (48 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (49 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (50 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (51 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (52 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (53 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (54 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (55 | (18 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (56 | (18 << 8))
#define MAP_UNION_ROOM               (57 | (18 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (19 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (19 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (19 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (9 | (19 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (10 | (19 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (11 | (19 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (12 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (13 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (14 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (15 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (16 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (17 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (18 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (19 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (20 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (21 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (22 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (23 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (24 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (25 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (26 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (27 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (28 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (29 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (30 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (31 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (32 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (33 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (34 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (35 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (36 | (19 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (37 | (19 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (38 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (39 | (19 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (40 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (41 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (42 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (43 | (19 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (44 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (45 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (46 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (47 | (19 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (48 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (49 | (19 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (50 | (19 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (51 | (19 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (52 | (19 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (53 | (19 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (54 | (19 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (55 | (19 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (56 | (19 << 8))
#define MAP_TRAINER_HILL_1F                                 (57 | (19 << 8))
#define MAP_TRAINER_HILL_2F                                 (58 | (19 << 8))
#define MAP_TRAINER_HILL_3F                                 (59 | (19 << 8))
#define MAP_TRAINER_HILL_4F                                 (60 | (19 << 8))
#define MAP_TRAINER_HILL_ROOF                               (61 | (19 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (62 | (19 << 8))

#define MAP_GROUPS_COUNT 20

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
