#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (0 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (0 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (0 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (0 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (0 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (0 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (0 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (0 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (0 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (0 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (0 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (0 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (0 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (0 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (0 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (0 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (0 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (0 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (0 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (0 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (0 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (0 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (0 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (0 << 8))
#define MAP_TRADE_CENTER             (25 | (0 << 8))
#define MAP_RECORD_CORNER            (26 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (0 << 8))
#define MAP_CONTEST_HALL             (28 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (0 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (0 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (0 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (0 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (0 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (0 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (40 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (41 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (42 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (43 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (44 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (45 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (46 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (47 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (48 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (49 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (50 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (51 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (52 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (53 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (54 | (0 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (55 | (0 << 8))
#define MAP_UNION_ROOM               (56 | (0 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (1 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (1 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (1 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (1 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (1 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (9 | (1 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (10 | (1 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (11 | (1 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (12 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (13 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (14 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (15 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (16 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (17 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (18 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (19 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (20 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (21 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (22 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (23 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (24 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (25 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (26 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (27 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (28 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (29 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (30 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (31 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (32 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (33 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (34 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (35 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (36 | (1 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (37 | (1 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (38 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (39 | (1 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (40 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (41 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (42 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (43 | (1 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (44 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (45 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (46 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (47 | (1 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (48 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (49 | (1 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (50 | (1 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (51 | (1 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (52 | (1 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (53 | (1 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (54 | (1 << 8))
#define MAP_TRAINER_HILL_1F                                 (55 | (1 << 8))
#define MAP_TRAINER_HILL_2F                                 (56 | (1 << 8))
#define MAP_TRAINER_HILL_3F                                 (57 | (1 << 8))
#define MAP_TRAINER_HILL_4F                                 (58 | (1 << 8))
#define MAP_TRAINER_HILL_ROOF                               (59 | (1 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (60 | (1 << 8))

#define MAP_GROUPS_COUNT 2

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
